"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EVENT_SCAN_ERROR = 'SCAN_ERROR';
exports.EVENT_SCAN_NULL_DEVICE = 'SCAN_NULL_DEVICE';
exports.EVENT_SCAN_DEVICE_FOUND = 'SCAN_DEVICE_FOUND';
exports.EVENT_CONNECT_ERROR = 'CONNECT_ERROR';
exports.EVENT_DISCOVERED_CHARACTERISTICS = 'DISCOVERED_CHARACTERISTICS';
exports.EVENT_LISTEN_ERROR = 'LISTEN_ERROR';
