export const EVENT_SCAN_ERROR = 'SCAN_ERROR';
export const EVENT_SCAN_NULL_DEVICE = 'SCAN_NULL_DEVICE';
export const EVENT_SCAN_DEVICE_FOUND = 'SCAN_DEVICE_FOUND';
export const EVENT_CONNECT_ERROR = 'CONNECT_ERROR';
export const EVENT_DISCOVERED_CHARACTERISTICS = 'DISCOVERED_CHARACTERISTICS';
export const EVENT_LISTEN_ERROR = 'LISTEN_ERROR';
